In [1]:
 # Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

In [2]:
# load csv exported in part 1 
df_countries = pd.read_csv('output_data/df_countries.csv')
df_countries = df_countries.drop(columns=['Unnamed: 0', 'index'])

In [3]:
df_countries.head()

,Latitude,City,Country,Longitude,Max Temperature (F),Humidity (%),Cloudiness (%),Wind Speed (mph),Date
0,-6.98,cabedelo,br,-34.83,84.20,70.0,75.0,11.41,1579897035
1,-20.73,mount isa,au,139.50,77.00,94.0,90.0,8.05,1579896813
2,-9.80,atuona,pf,-139.03,80.71,75.0,21.0,12.15,1579897036
3,-2.02,lorengau,pg,147.27,83.62,68.0,9.0,5.19,1579897036
4,-10.75,tinyahuarco,pe,-76.30,39.79,91.0,100.0,5.08,1579897036

In [4]:
# configure gmaps 
# use lat and lng as locations, humidity as weight
# add heatmap layer to map 
locations = df_countries[['Latitude', 'Longitude']]
weights = df_countries['Humidity (%)']

fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights = weights,
                                dissipating = False, max_intensity=15,
                                point_radius=2)

fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

In [5]:
# create df that finds the weather conditions given: 
# temperature higher than 70, lower than 80
# wind speed less than 10 mph
# zero cloudiness

vacation_df = df_countries.loc[(df_countries['Max Temperature (F)'] > 75) & (df_countries['Max Temperature (F)'] < 85), :]
vacation_df = vacation_df.loc[vacation_df['Wind Speed (mph)'] < 10, :]
vacation_df = vacation_df.loc[vacation_df['Cloudiness (%)'] == 0, :]

In [6]:
vacation_df = vacation_df.reset_index()
vacation_df = vacation_df.drop(columns='index')
vacation_df

,Latitude,City,Country,Longitude,Max Temperature (F),Humidity (%),Cloudiness (%),Wind Speed (mph),Date
0,12.48,oussouye,sn,-16.55,84.20,51.0,0.0,4.70,1579897284
1,-33.70,chuy,uy,-53.46,80.91,52.0,0.0,7.31,1579897381
2,-34.48,rocha,uy,-54.33,84.27,41.0,0.0,6.35,1579897134
3,-20.32,port hedland,au,118.57,82.40,88.0,0.0,6.08,1579897382
4,18.20,les cayes,ht,-73.75,79.63,61.0,0.0,7.09,1579897382
5,5.79,anloga,gh,0.90,84.20,66.0,0.0,4.70,1579897463
6,-38.55,necochea,ar,-58.74,75.99,76.0,0.0,4.00,1579897546

In [40]:
hotel_df = vacation_df
hotel_df['Hotel Name'] = np.nan

target_search = "Hotel"
target_radius = 5000
target_type = "lodging"

idx = 0
for index, row in hotel_df.iterrows():
    # set up a parameters dictionary
    params = {
        "location": f"{row['Latitude']}, {row['Longitude']}",
        "keyword": target_search,
        "radius": target_radius,
        "type": target_type,
        "key": g_key
    }

    # base url
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # run a request using our params dictionary
    response = requests.get(base_url, params=params)
    response_json = response.json()
    results = response_json['results']
    if len(results) > 0:
        name = response_json['results'][0]['name']
        hotel_df.iloc[idx, -1] = name
    idx = idx + 1

narrowed_city_df = hotel_df

In [43]:
narrowed_city_df

,Latitude,City,Country,Longitude,Max Temperature (F),Humidity (%),Cloudiness (%),Wind Speed (mph),Date,Hotel,Hotel Name
0,12.48,oussouye,sn,-16.55,84.20,51.0,0.0,4.70,1579897284,,Hotel Carabane
1,-33.70,chuy,uy,-53.46,80.91,52.0,0.0,7.31,1579897381,,Bertelli Chuí Hotel
2,-34.48,rocha,uy,-54.33,84.27,41.0,0.0,6.35,1579897134,,Hotel Trocadero
3,-20.32,port hedland,au,118.57,82.40,88.0,0.0,6.08,1579897382,,The Esplanade Hotel
4,18.20,les cayes,ht,-73.75,79.63,61.0,0.0,7.09,1579897382,,Hôtel Le Méridien
5,5.79,anloga,gh,0.90,84.20,66.0,0.0,4.70,1579897463,,BeatzWave Studios
6,-38.55,necochea,ar,-58.74,75.99,76.0,0.0,4.00,1579897546,,Hotel Ñikén Spa & Business Center

In [45]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in narrowed_city_df.iterrows()]
locations = hotel_df[["Latitude", "Longitude"]]

In [47]:
# add marker layer ontop of heat map 

marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
fig

Figure(layout=FigureLayout(height='420px'))